### Ejemplo 1

In [1]:
from numpy  import *

In [2]:
a = arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

### Ejemplo 2

In [13]:
from numpy  import *

In [14]:
a = array( [2,3,4] )

In [15]:
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b = array([1.2, 3.5, 5.1])

In [18]:
b.dtype

dtype('float64')

### Ejemplo 3

In [19]:
b = array( [ (1.5,2,3), (4,5,6) ] )

In [20]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

### Ejemplo 4

In [21]:
c = array( [ [1,2], [3,4] ], dtype=complex )

In [22]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

### Ejemplo 5

In [23]:
zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
ones( (2,3,4), dtype=int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### Ejemplo 6

In [26]:
arange( 10, 30, 5 ) # equivalente a MATLAB: 10:5:30

array([10, 15, 20, 25])

In [27]:
arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

### Ejemplo 7

In [28]:
linspace( 0, 2, 9 ) # 9 es el número de elementos que queremos

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [29]:
x = linspace( 0, 2*pi, 100 )

In [30]:
f = sin(x)

### Ejemplo 8

In [31]:
a = arange(6)

In [32]:
print a

[0 1 2 3 4 5]


In [33]:
b = arange(12).reshape(4,3)

In [34]:
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [35]:
c = arange(24).reshape(2,3,4) # reshape(nº listas, n, m)

In [36]:
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Ejemplo 9

In [37]:
a = array( [20,30,40,50] )

In [38]:
a

array([20, 30, 40, 50])

In [39]:
b = arange( 4 )

In [40]:
b

array([0, 1, 2, 3])

In [41]:
c = a-b

In [42]:
c

array([20, 29, 38, 47])

In [43]:
b**2

array([0, 1, 4, 9])

In [44]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [45]:
a<35

array([ True,  True, False, False], dtype=bool)

### Ejemplo 10

In [46]:
A = array( [[1,1],
            [0,1]] )

In [47]:
B = array( [[2,0],
            [3,4]] )

In [48]:
A*B 

array([[2, 0],
       [0, 4]])

In [49]:
dot(A,B) 

array([[5, 4],
       [3, 4]])

### Ejemplo 11

In [50]:
a = ones((2,3), dtype=int)

In [51]:
b = random.random((2,3))

In [52]:
 a *= 3

In [53]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [54]:
b += a

In [55]:
b

array([[ 3.34944531,  3.24582339,  3.21260271],
       [ 3.21035818,  3.97634673,  3.25450453]])

In [56]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
a

### Ejemplo 12

In [ ]:
a = ones(3, dtype=int32)

In [ ]:
b = linspace(0,pi,3)

In [ ]:
b.dtype.name

In [ ]:
c = a+b

In [ ]:
c

In [ ]:
c.dtype.name

In [ ]:
d = exp(c*1j)

In [ ]:
d

In [ ]:
d.dtype.name

### Ejemplo 13

In [ ]:
a = random.random((2,3))

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

### Ejemplo 14

In [ ]:
b = arange(12).reshape(3,4)

In [ ]:
b

In [ ]:
b.sum(axis=0)

In [ ]:
b.min(axis=1)

In [ ]:
b.cumsum(axis=1)

### Ejemplo 15

In [ ]:
B = arange(3)

In [ ]:
B

In [ ]:
exp(B)

In [ ]:
sqrt(B)

In [ ]:
C = array([2., -1., 4.])

In [ ]:
add(B, C)

### Ejemplo 16

In [ ]:
a = arange(10)**3

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[:6:2] = -1000 

In [ ]:
a

In [ ]:
a[ : :-1]

### Ejemplo 17

In [ ]:
b=array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
b[2,3]

In [ ]:
b[0:5, 1]

In [ ]:
b[ : ,1]

In [ ]:
b[1:3, : ]

### Ejemplo 18

In [ ]:
b[-1]

### Ejemplo 19

In [ ]:
c = array( [ [[  0,  1,  2],[ 10, 12, 13]],[[100,101,102],[110,112,113]] ] )

In [ ]:
c.shape

In [ ]:
c[1,...]  

In [ ]:
c[...,2] 

### Ejemplo 20

In [ ]:
for i in a:
    print i**(1/3.)

In [ ]:
for row in b:
    print row

### Ejemplo 21

In [ ]:
for element in b.flat:
    print element,

### Ejemplo 22

In [ ]:
a=array([[ 7.,  5.,  9.,  3.],
       [ 7.,  2.,  7.,  8.],
       [ 6.,  8.,  3.,  2.]])

In [ ]:
a.shape

In [ ]:
a.ravel()

In [ ]:
a.shape = (6, 2)

In [ ]:
a.transpose()

### Ejemplo 23

In [ ]:
a

In [ ]:
a.resize((2,6))

In [ ]:
a

### Ejemplo 24

In [ ]:
a= array([[ 1.,  1.],
       [ 5.,  8.]])

In [ ]:
 b = array([[ 3.,  3.],
       [ 6.,  0.]])

In [ ]:
vstack((a,b))

In [ ]:
hstack((a,b))

### Ejemplo 25

In [ ]:
a= array([[ 8.,  8.,  3.,  9.,  0.,  4.,  3.,  0.,  0.,  6.,  4.,  4.],
       [ 0.,  3.,  2.,  9.,  6.,  0.,  4.,  5.,  7.,  5.,  1.,  4.]])

In [ ]:
hsplit(a,3)

In [ ]:
hsplit(a,(3,4))

### Ejemplo 26

In [ ]:
 a = arange(12)

In [ ]:
b = a

In [ ]:
b is a

In [ ]:
b.shape = 3,4

In [ ]:
a.shape

### Ejemplo 27

In [ ]:
c = a.view()

In [ ]:
c is a

In [ ]:
c.shape = 2,6

In [ ]:
a.shape

In [ ]:
c[0,4] = 1234

In [ ]:
a

### Ejemplo 28

In [ ]:
d = a.copy()

In [ ]:
 d is a

In [ ]:
d[0,0] = 9999

In [ ]:
a

### Ejemplo 29

In [ ]:
bools=array([False, False, True,True])

In [ ]:
bools.any()

In [ ]:
bools.all()

### Ejemplo 30

In [ ]:
arr=array([0.609,0.462, 0.098,0.123,0.987,0.0185,-1.345,-0.567])

In [ ]:
arr.sort()

In [ ]:
arr

In [ ]:
b=array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [ ]:
b.sort(1)

In [ ]:
b

### Ejemplo 31

In [ ]:
from numpy.polynomial import Polynomial as P

In [ ]:
polinomio=P([1,2,3])

In [ ]:
print(polinomio)

In [ ]:
print(polinomio+polinomio)

### Ejemplo 32

In [ ]:
a= array([2,34,4])

In [ ]:
b=array([2,5,6])

In [ ]:
z=inner(a,b)

In [ ]:
z

In [ ]:
z=outer(a,b)

In [ ]:
z

In [ ]:
z=cross(a,b)

In [ ]:
z

### Ejemplo 33

In [ ]:
m=matrix([[2,3],[3,2]])

In [ ]:
m

In [ ]:
n=matrix([[1,2],[-5,2]])

In [ ]:
n

In [ ]:
n+m

### Ejemplo 34

In [ ]:
import numpy.random as R

In [ ]:
arr=R.randn(5,4)

In [ ]:
arr.mean()

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)

### Ejemplo 35

In [ ]:
nombres1=array(["Juan","Luisa","Juan","Antonio","Pepe", "José","Daniel","Eva"])

In [ ]:
nombres2=array(["Juan","Maria","Juan","Alfonso","Pepe", "Laura","Daniel","Eva"])

In [ ]:
unique(nombres1)

In [ ]:
intersect1d(nombres1,nombres2)

In [ ]:
union1d(nombres1,nombres2)

### Ejemplo 36

In [ ]:
from numpy.linalg import inv,qr

In [ ]:
x=array([[1,2,3],[4,5,6]])

In [ ]:
y=array([[6,7],[4,8],[9,20]])

In [ ]:
z=x.dot(y)

In [ ]:
inv(z)

In [ ]:
q,r=qr(z)

In [ ]:
r

### Ejemplo 37

In [ ]:
casos=R.normal(size=(4,4))

In [ ]:
casos

### Ejemplo 38

In [ ]:
import numpy

In [ ]:
import pylab

In [ ]:
mu, sigma = 2, 0.5

In [ ]:
v = numpy.random.normal(mu,sigma,10000)

In [ ]:
(n, bins) = numpy.histogram(v, bins=50, normed=True)

In [ ]:
pylab.plot(.5*(bins[1:]+bins[:-1]), n)

In [ ]:
pylab.show()