### Práctica

### Ejercicios de Numpy

In [2]:
import numpy as np

#### Ejercicio 1:  Crear una matriz 8x8  y rellenarla con 1´s de manera intercalada

In [3]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print Z

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Ejercicio 2:  Crear una matriz 10x10  con valores aleatorios y encontrar el valor máximo y mínimo 

In [3]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print Zmin, Zmax

0.00421983555662 0.994443868042


#### Ejercicio 3: Multiplicar una matriz 5x3 por una matriz de 3x2 

In [4]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print Z

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### Ejercicio 4: Normalizar una matriz de valores aleatorios de 5x5(entre 0 y 1)

In [6]:
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print Z

[[ 0.49379576  0.11484369  0.17845075  0.48322614  0.57844919]
 [ 0.58653597  0.19295387  0.61073548  0.92433811  0.85641333]
 [ 0.90867953  0.5227      1.          0.42687056  0.26829633]
 [ 0.53447675  0.6697294   0.01431591  0.          0.22933858]
 [ 0.31528029  0.10474725  0.1091529   0.78753147  0.84991439]]


#### Ejercicio 5: Crear un vector de tamaño 10 y ordenarlo

In [7]:
Z = np.random.random(10)
Z.sort()
print Z

[ 0.02056105  0.16107383  0.24755536  0.29221426  0.3217645   0.37790518
  0.56023122  0.6727074   0.91017037  0.98969167]


#### Ejercicio 6: Crear un matriz de 5x5 con valores en las filas de 0 a 4

In [8]:
Z = np.zeros((5,5))
Z += np.arange(5)
print Z

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### Ejercicio 7: Crear un vector de tamaño 10 con valores entre 0 y 1, ambos excluidos.

In [9]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print Z

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### Ejercicio 8: Considerar 2 arrays A y B aleatorios, y comprobar si son iguales.

In [10]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print equal

False


#### Ejercicio 9: Crear un vector aleatorio de tamaño 30 y encontrar la media.

In [11]:
Z = np.random.random(30)
m = Z.mean()
print m

0.478126835994


#### Ejercicio 10: Crear un vector aleatorio de tamaño 10 y reemplazar el máximo valor por 0

In [13]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print Z

[ 0.          0.82183516  0.53267701  0.53322772  0.33276902  0.24960997
  0.10885874  0.38898769  0.16005688  0.50567514]


#### Ejercicio 11: Crear un array estructurado representando una posición (x,y) y un color (r,g,b)

In [14]:
 Z = np.zeros(10, [ ('posicion', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print Z

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


#### Ejercicio 12: Considerar un vector aleatorio con tamaño (100,2), representando coordenadas. Encontrar las distancias punto a punto.

In [15]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print D

[[ 0.          0.16833016  0.72441292  0.24982316  0.30569618  0.57537458
   0.44172888  0.29285555  0.44069854  0.60157507]
 [ 0.16833016  0.          0.75024003  0.08402354  0.47146352  0.74229364
   0.30488665  0.32469696  0.60803664  0.54448355]
 [ 0.72441292  0.75024003  0.          0.75202163  0.71096195  0.97215704
   0.66010671  0.43556398  0.78258637  0.36177088]
 [ 0.24982316  0.08402354  0.75202163  0.          0.54861513  0.82500181
   0.23295652  0.34762384  0.68640095  0.5091975 ]
 [ 0.30569618  0.47146352  0.71096195  0.54861513  0.          0.30961751
   0.70147111  0.39511569  0.13896199  0.74248918]
 [ 0.57537458  0.74229364  0.97215704  0.82500181  0.30961751  0.
   1.00159602  0.70384648  0.19283293  1.0488192 ]
 [ 0.44172888  0.30488665  0.66010671  0.23295652  0.70147111  1.00159602
   0.          0.37060534  0.8393199   0.33943975]
 [ 0.29285555  0.32469696  0.43556398  0.34762384  0.39511569  0.70384648
   0.37060534  0.          0.51938481  0.34958279]
 [ 0.440

#### Ejercicio 13: Encontrar el valor más cercano a un valor dado en un array.

In [16]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print m

0.512180283229


#### Ejercicio 14: Considerar un array de dimensión (5,5,3) y una array (5,5). Se pide buscar un método para multiplicarlos.

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print A * B[:,:,None]

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


#### Ejercicio 15: Considerar un matriz aleatoria de 10x2 representando coordenadas cartesianas, convertir a coordenadas polares.

In [20]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print R
print T

[ 0.93691729  0.57483699  0.92601693  0.34363875  0.92217009  1.01325189
  0.33757796  1.05105966  0.18818722  0.8483173 ]
[ 1.45779431  1.2069997   1.18208399  0.75021057  1.46355228  0.2334388
  0.52228329  0.745935    1.21383652  1.11694564]


#### Ejercicio 16: Imprimir el mínimo y máximo valor representable por cada tipo de escalar de numpy.

In [19]:
for dtype in [np.int8, np.int32, np.int64]:
 print np.iinfo(dtype).min
 print np.iinfo(dtype).max

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### Ejercicio 17: Dado un array cambiar dos filas de posición.

In [18]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print A

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Ejercicio 18: Considerar el vector [1,2,3,4,5], construir a partir del mismos un nuevo vector con 3 ceros consecutivos intercalados entre cada valor.

In [17]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print Z0

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


### Ejercicios de Pandas

In [1]:
import pandas as pd
import numpy as np

#### Ejercicio 1: Crear una serie con los valores 2.0, 1.0, 5.0, 0.97, 3.0, 10.0, 0.0599, 8.0

In [4]:
values = np.array([2.0, 1.0, 5.0, 0.97, 3.0, 10.0, 0.0599, 8.0])
ser = pd.Series(values)
print ser

0     2.0000
1     1.0000
2     5.0000
3     0.9700
4     3.0000
5    10.0000
6     0.0599
7     8.0000
dtype: float64


#### Ejercicio 2: Crear una serie con los valores 2.0, 1.0, 5.0, 0.97, 3.0, 10.0, 0.0599, 8.0 y las etiquetas 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'

In [6]:
values = np.array([2.0, 1.0, 5.0, 0.97, 3.0, 10.0, 0.0599, 8.0])
labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
ser = pd.Series(data=values, index=labels)
print ser

A     2.0000
B     1.0000
C     5.0000
D     0.9700
E     3.0000
F    10.0000
G     0.0599
H     8.0000
dtype: float64


#### Ejercicio 3: Crear una serie que represente los datos de una película. Mostrar los índices, valores, y cómo se puede acceder a los valores mediante índices.

In [7]:
pelicula = {
    'edad': 1,
    'sexo': 'F',
    'genero': 'Drama',
    'identificador': 1193,
    'ocupación': 10,
    'calificación': 5,
    'temporización': 978300760,
    'titulo': "Los cañones del Navarone",
    'ident-usuario': 1,
    'código': '48067'
    }
ser = pd.Series(pelicula)
print ser

calificación                            5
código                              48067
edad                                    1
genero                              Drama
ident-usuario                           1
identificador                        1193
ocupación                              10
sexo                                    F
temporización                   978300760
titulo           Los cañones del Navarone
dtype: object


In [9]:
ser.index

Index([u'calificación', u'código', u'edad', u'genero', u'ident-usuario', u'identificador', u'ocupación', u'sexo', u'temporización', u'titulo'], dtype='object')

In [10]:
ser.values

array([5, '48067', 1, 'Drama', 1, 1193, 10, 'F', 978300760,
       'Los ca\xc3\xb1ones del Navarone'], dtype=object)

In [11]:
ser[0]

5

In [12]:
ser['sexo']

'F'

In [13]:
ser.get_value('genero')

'Drama'

#### Ejercicio 4: Sumar dos series con diferentes índices.

In [14]:
ser_1 = pd.Series(data=[1,3,4], index=['A', 'B', 'C'])
ser_2 = pd.Series(data=[5,5,5], index=['A', 'G', 'C'])
print ser_1 + ser_2

A     6
B   NaN
C     9
G   NaN
dtype: float64


#### Ejercicio 5: Construir un dataframe a partir de un diccionario

In [15]:
pd.DataFrame({'col_1': [0.12, 7, 45, 10], 'col_2': [0.9, 9, 34, 11]})

col_1  col_2
0   0.12    0.9
1   7.00    9.0
2  45.00   34.0
3  10.00   11.0

#### Ejercicio 6: Construir un dataframe a partir de un diccionario, indicando nombres de columnas y filas.

In [16]:
pd.DataFrame(data={'col_1': [0.12, 7, 45, 10], 'col_2': [0.9, 9, 34, 11]},
             columns=['col_1', 'col_2', 'col_3'])

col_1  col_2 col_3
0   0.12    0.9   NaN
1   7.00    9.0   NaN
2  45.00   34.0   NaN
3  10.00   11.0   NaN

#### Ejercicio 7: Construir un dataframe a partir de un diccionario de series.

In [17]:
pelicula = {
    'edad': 1,
    'sexo': 'F',
    'genero': 'Drama',
    'identificador': 1193,
    'ocupación': 10,
    'calificación': 5,
    'temporización': 978300760,
    'titulo': "Los cañones del Navarone",
    'ident-usuario': 1,
    'código': '48067'
    }
ser_1 = pd.Series(pelicula)
ser_2 = pd.Series(pelicula)
df = pd.DataFrame({'r_1': ser_1, 'r_2': ser_2})
df.columns.name = 'eventos'
df.index.name = 'datos'
df

eventos                             r_1                       r_2
datos                                                            
calificación                          5                         5
código                            48067                     48067
edad                                  1                         1
genero                            Drama                     Drama
ident-usuario                         1                         1
identificador                      1193                      1193
ocupación                            10                        10
sexo                                  F                         F
temporización                 978300760                 978300760
titulo         Los cañones del Navarone  Los cañones del Navarone

#### Ejercicio 8: Transponer el dataframe creado en el ejercicio anterior. Obtener los nombres de las columnas, las filas y los valores.

In [18]:
df = df.T
df

datos   calificación código edad genero ident-usuario identificador ocupación  \
eventos                                                                         
r_1                5  48067    1  Drama             1          1193        10   
r_2                5  48067    1  Drama             1          1193        10   

datos   sexo temporización                    titulo  
eventos                                               
r_1        F     978300760  Los cañones del Navarone  
r_2        F     978300760  Los cañones del Navarone

In [19]:
df.columns 

Index([u'calificación', u'código', u'edad', u'genero', u'ident-usuario', u'identificador', u'ocupación', u'sexo', u'temporización', u'titulo'], dtype='object')

In [20]:
df.index

Index([u'r_1', u'r_2'], dtype='object')

In [21]:
df.values

array([[5, '48067', 1, 'Drama', 1, 1193, 10, 'F', 978300760,
        'Los ca\xc3\xb1ones del Navarone'],
       [5, '48067', 1, 'Drama', 1, 1193, 10, 'F', 978300760,
        'Los ca\xc3\xb1ones del Navarone']], dtype=object)

#### Ejercicio 9: Eliminar y añadir filas y columnas al ejemplo anterior.

In [4]:
df = pd.DataFrame({'r_1': ser_1, 'r_2': ser_2})
df.drop('genero', axis=0)

NameError: name 'ser_1' is not defined

In [23]:
df.drop('r_1', axis=1)

r_2
datos                                  
calificación                          5
código                            48067
edad                                  1
genero                            Drama
ident-usuario                         1
identificador                      1193
ocupación                            10
sexo                                  F
temporización                 978300760
titulo         Los cañones del Navarone

In [27]:
df['r_3'] = [4,3456,3,'Drama', 1195, 5, 978300760, 'M', 10009,'ET']
df

r_1                       r_2        r_3
datos                                                                       
calificación                          5                         5          4
código                            48067                     48067       3456
edad                                  1                         1          3
genero                            Drama                     Drama      Drama
ident-usuario                         1                         1       1195
identificador                      1193                      1193          5
ocupación                            10                        10  978300760
sexo                                  F                         F          M
temporización                 978300760                 978300760      10009
titulo         Los cañones del Navarone  Los cañones del Navarone         ET

#### Ejercicio 10: Crear un dataframe e indexar usando el nombre de la columna o bien usando la notación “.”

In [2]:
df = pd.DataFrame(data={'col_1': [0.12, 7, 45, 10], 'col_2': [0.9, 9, 34, 11]},
                  columns=['col_1', 'col_2', 'col_3'],
                  index=['obs1', 'obs2', 'obs3', 'obs4'])
df['col_1']

obs1     0.12
obs2     7.00
obs3    45.00
obs4    10.00
Name: col_1, dtype: float64

In [29]:
df.col_1

obs1     0.12
obs2     7.00
obs3    45.00
obs4    10.00
Name: col_1, dtype: float64

#### Ejercicio 11: En el dataframe anterior seleccionar un subconjunto de columnas.

In [30]:
df[['col_2', 'col_1']]

col_2  col_1
obs1    0.9   0.12
obs2    9.0   7.00
obs3   34.0  45.00
obs4   11.0  10.00